PreCommit:
  EsLint:
    enabled: true
    required_executable: './client/node_modules/.bin/eslint'
    include:
      - '**/*.js'
      - '**/*.jsx'

  HamlLint:
    enabled: true

  HardTabs:
    enabled: true

  RailsSchemaUpToDate:
    enabled: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']

  ScssLint:
    enabled: true

  YamlSyntax:
    enabled: true
