default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password:

development:
  <<: *default
  database: shelf_development

test:
  <<: *default
  database: shelf_test

production:
  <<: *default
  database: shelf_production
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV['DB_PASSWORD'] %>
